name = "Sample Project"
description = "This is a model for Sample Project"


[dirs]
project = '/sample_project'
train = 'train'
valid = 'valid'
test = 'test'
pred = 'pred'


[[models]]
model = "IncrementalPCA"
name = "ipca"
n_node = 10
n_cpu = 8

[models.params]
n_components = [1, 3, 5]
whiten = [true, false]
batch_size = [20]

[models.methods]
train = "partial_fit"
pred = "transform"

[[models.scores]]
name = "explained_variance_ratio_"
attribute = true


[[models]]
model = "MiniBatchKMeans"
name = "mini_batch_kmeans"
n_node = 10
n_cpu = 8

[models.params]
n_clusters = [1, 3, 5, 7, 9]
init = ["k-means++"]
batch_size = [20, 30]

[models.methods]
train = "partial_fit"
pred = "predict"

[[models.scores]]
name = "inertia_"
attribute = true


[[selections]]
criteria = 'inertia_'
method = 'elbow'
